# Generated by Django 4.2.7 on 2023-11-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('PRICE', models.IntegerField(null=True)),
                ('ESTIMATED_PRICE', models.IntegerField(null=True)),
                ('NO_PRICE', models.CharField(choices=[('CP', 'Copy from another cost'), ('DF', 'Use a default value')], default='DF', max_length=20)),
                ('DEFAULT_PRICE', models.IntegerField(null=True)),
                ('PRICE_TO_COPY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apts.cost')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SQUARE_METERS', models.IntegerField()),
                ('ROOMS', models.IntegerField()),
                ('LOCATION', models.CharField(blank=True, max_length=256)),
                ('NOTES', models.CharField(blank=True, max_length=512)),
                ('COSTS', models.ManyToManyField(to='apts.cost')),
            ],
        ),
    ]
