# Generated by Django 4.2.7 on 2023-11-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apts', '0002_apartment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='DEFAULT_PRICE',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='ESTIMATED_PRICE',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='NO_PRICE',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='PRICE_TO_COPY',
        ),
        migrations.AddField(
            model_name='cost',
            name='PRICE_IS_ESTIMATED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cost',
            name='TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apts.costtype'),
        ),
    ]
