# Generated by Django 4.2.7 on 2023-11-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apts', '0003_costtype_remove_cost_default_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='COSTS',
            field=models.ManyToManyField(blank=True, to='apts.cost'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='TYPE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apts.costtype'),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='NAME',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
