# Generated by Django 4.2.7 on 2023-11-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apts', '0004_alter_apartment_costs_alter_cost_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50, unique=True)),
                ('IS', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
