# Generated by Django 4.2.7 on 2023-12-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apts', '0005_attribute_predefinedattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ATTRIBUTES',
            field=models.ManyToManyField(blank=True, to='apts.attribute'),
        ),
    ]
